# light의 경우, state_topic의 group은 RS485 패킷에 보이는 두자리 숫자이고,
# command_topic의 group은 1부터 연속되는 숫자입니다.
light:
  - platform: mqtt
    name: "Living Room 1"
    state_topic: "sds/light/21/power1/state"
    command_topic: "sds/light/1/power/command"
  - platform: mqtt
    name: "Living Room 2"
    state_topic: "sds/light/21/power2/state"
    command_topic: "sds/light/2/power/command"
  - platform: mqtt
    name: "Master Bedroom"
    state_topic: "sds/light/13/power1/state"
    command_topic: "sds/light/3/power/command"
  - platform: mqtt
    name: "Bedroom 1"
    state_topic: "sds/light/14/power1/state"
    command_topic: "sds/light/4/power/command"
  - platform: mqtt
    name: "Bedroom 2"
    state_topic: "sds/light/15/power1/state"
    command_topic: "sds/light/5/power/command"

fan:
  - platform: mqtt
    name: "Fan1"
    state_topic: "sds/fan/1/power/state"
    command_topic: "sds/fan/1/power/command"
    speed_state_topic: "sds/fan/1/speed/state"
    speed_command_topic: "sds/fan/1/speed/command"
    # 아래 payload 내용은 수정하지 마세요
    payload_on: 5
    payload_off: 6
    payload_low_speed: 3
    payload_medium_speed: 2
    payload_high_speed: 1
    speeds:
      - low
      - medium
      - high

climate:
  - platform: mqtt
    name: "Living Room"
    mode_state_topic: "sds/thermostat/1/state"
    mode_command_topic: "sds/thermostat/1/power/command"
    temperature_state_topic: "sds/thermostat/1/target/state"
    temperature_command_topic: "sds/thermostat/1/target/command"
    current_temperature_topic: "sds/thermostat/1/current/state"
    modes:
      - "off"
      - "heat"
    min_temp: 18
    max_temp: 26

  - platform: mqtt
    name: "Master Bedroom"
    mode_state_topic: "sds/thermostat/2/state"
    mode_command_topic: "sds/thermostat/2/power/command"
    temperature_state_topic: "sds/thermostat/2/target/state"
    temperature_command_topic: "sds/thermostat/2/target/command"
    current_temperature_topic: "sds/thermostat/2/current/state"
    modes:
      - "off"
      - "heat"
    min_temp: 18
    max_temp: 26

  - platform: mqtt
    name: "Bedroom 1"
    mode_state_topic: "sds/thermostat/3/state"
    mode_command_topic: "sds/thermostat/3/power/command"
    temperature_state_topic: "sds/thermostat/3/target/state"
    temperature_command_topic: "sds/thermostat/3/target/command"
    current_temperature_topic: "sds/thermostat/3/current/state"
    modes:
      - "off"
      - "heat"
    min_temp: 18
    max_temp: 26

  - platform: mqtt
    name: "Bedroom 2"
    mode_state_topic: "sds/thermostat/4/state"
    mode_command_topic: "sds/thermostat/4/power/command"
    temperature_state_topic: "sds/thermostat/4/target/state"
    temperature_command_topic: "sds/thermostat/4/target/command"
    current_temperature_topic: "sds/thermostat/4/current/state"
    modes:
      - "off"
      - "heat"
    min_temp: 18
    max_temp: 26

sensor:
# - platform: rest
#   resource: "https://hass.printk.info/api/hassio/addons/25b6f150_wallpad/info"
#   headers:
#     Authorization: !secret ha_long_token_bearer
#     Content-Type: application/json
#   name: wallpad_addon_state
#   value_template: "{{value_json['data']['state']}}"
#   scan_interval: 60
  - platform: template
    sensors:
      fan_speed_value:
        unit_of_measurement: '단'
        value_template: >-
          {% if states.fan.fan1.state == 'off'  -%}
            0
          {% elif states.fan.fan1.attributes.speed == 'low' -%}
            1
          {% elif states.fan.fan1.attributes.speed == 'medium' -%}
            2
          {%- else -%}
            3
          {%- endif %}

  - platform: mqtt
    name: "Gas Valve Status"
    state_topic: "sds/gas_valve/1/power/state"
    value_template: >-
      {% if states.sensor.gas_valve_status.state == 'OFF' -%}
        열림
      {%- else -%}
        차단
      {%- endif %}

  - platform: mqtt
    name: "Living Room Power Usage 1"
    state_topic: "sds/plug/1/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Living Room Power Usage 2"
    state_topic: "sds/plug/2/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Master Bedroom Power Usage 1"
    state_topic: "sds/plug/3/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Master Bedroom Power Usage 2"
    state_topic: "sds/plug/4/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Bedroom 1 Power Usage 1"
    state_topic: "sds/plug/5/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Bedroom 1 Power Usage 2"
    state_topic: "sds/plug/6/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Bedroom 2 Power Usage 1"
    state_topic: "sds/plug/7/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Bedroom 2 Power Usage 2"
    state_topic: "sds/plug/8/current/state"
    unit_of_measurement: "W"
  - platform: mqtt
    name: "Power Consumption"
    state_topic: "sds/energy/0/current/state"
    unit_of_measurement: "Wh"
  - platform: mqtt
    name: "Gas Consumption"
    state_topic: "sds/energy/1/current/state"
    unit_of_measurement: "m³"
  - platform: mqtt
    name: "Water Consumption"
    state_topic: "sds/energy/2/current/state"
    unit_of_measurement: "m³"

switch:
# - platform: template
#   switches:
#     wallpad_addon_state:
#       value_template: "{{ is_state('sensor.wallpad_addon_state', 'started') }}"
#       turn_on:
#         service: hassio.addon_start
#         data:
#           addon: "25b6f150_wallpad"
#       turn_off:
#         service: hassio.addon_stop
#         data:
#           addon: "25b6f150_wallpad"

    # 아래 세가지는 현관 스위치
  - platform: mqtt
    name: "Call Elevator"
    state_topic: "sds/entrance/ev/state"
    command_topic: "sds/entrance/ev/command"
    icon: 'mdi:elevator'
  - platform: mqtt
    name: "Close Gas Valve"
    state_topic: "sds/entrance/gas/state"
    command_topic: "sds/entrance/gas/command"
    icon: 'mdi:valve'
  - platform: mqtt
    name: "Turn Off All Lights" # 'full' 모드에서만 사용 가능
    state_topic: "sds/entrance/light/state"
    command_topic: "sds/entrance/light/command"
    icon: 'mdi:lightbulb-group-off'

    # 나머지는 월패드 기능
  - platform: mqtt
    name: "Living Room Plug Power 1"
    state_topic: "sds/plug/1/power/state"
    command_topic: "sds/plug/1/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Living Room Plug Power 2"
    state_topic: "sds/plug/2/power/state"
    command_topic: "sds/plug/2/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Master Bedroom Plug Power 1"
    state_topic: "sds/plug/3/power/state"
    command_topic: "sds/plug/3/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Master Bedroom Plug Power 2"
    state_topic: "sds/plug/4/power/state"
    command_topic: "sds/plug/4/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Bedroom 1 Plug Power 1"
    state_topic: "sds/plug/5/power/state"
    command_topic: "sds/plug/5/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Bedroom 1 Plug Power 2"
    state_topic: "sds/plug/6/power/state"
    command_topic: "sds/plug/6/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Bedroom 2 Plug Power 1"
    state_topic: "sds/plug/7/power/state"
    command_topic: "sds/plug/7/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Bedroom 2 Plug Power 2"
    state_topic: "sds/plug/8/power/state"
    command_topic: "sds/plug/8/power/command"
    icon: 'mdi:power-plug'
  - platform: mqtt
    name: "Living Room Plug IdleCut 1"
    state_topic: "sds/plug/1/idlecut/state"
    command_topic: "sds/plug/1/idlecut/command"
    icon: 'mdi:leaf'
  - platform: mqtt
    name: "Living Room Plug IdleCut 2"
    state_topic: "sds/plug/2/idlecut/state"
    command_topic: "sds/plug/2/idlecut/command"
    icon: 'mdi:leaf'
  - platform: mqtt
    name: "Master Bedroom Plug IdleCut 1"
    state_topic: "sds/plug/3/idlecut/state"
    command_topic: "sds/plug/3/idlecut/command"
    icon: 'mdi:leaf'
  - platform: mqtt
    name: "Master Bedroom Plug IdleCut 2"
    state_topic: "sds/plug/4/idlecut/state"
    command_topic: "sds/plug/4/idlecut/command"
    icon: 'mdi:leaf'
  - platform: mqtt
    name: "Bedroom 1 Plug IdleCut 1"
    state_topic: "sds/plug/5/idlecut/state"
    command_topic: "sds/plug/5/idlecut/command"
    icon: 'mdi:leaf'
  - platform: mqtt
    name: "Bedroom 1 Plug IdleCut 2"
    state_topic: "sds/plug/6/idlecut/state"
    command_topic: "sds/plug/6/idlecut/command"
    icon: 'mdi:leaf'
  - platform: mqtt
    name: "Bedroom 2 Plug IdleCut 1"
    state_topic: "sds/plug/7/idlecut/state"
    command_topic: "sds/plug/7/idlecut/command"
    icon: 'mdi:leaf'
  - platform: mqtt
    name: "Bedroom 2 Plug IdleCut 2"
    state_topic: "sds/plug/8/idlecut/state"
    command_topic: "sds/plug/8/idlecut/command"
    icon: 'mdi:leaf'

script:
  sds_light_all_off:
    sequence:
    - service: light.turn_off
      entity_id: light.living_room_1
    - service: light.turn_off
      entity_id: light.living_room_2
    - service: light.turn_off
      entity_id: light.master_bedroom
    - service: light.turn_off
      entity_id: light.bedroom_1
    - service: light.turn_off
      entity_id: light.bedroom_2

# 아래 input_boolean과 automation은 환기 꺼짐/1단/2단/3단 버튼 용도
input_boolean:
  fan_off:
    name: "환기"
    icon: mdi:circle-off-outline
  fan_low:
    name: "1단"
    icon: mdi:circle-slice-3
  fan_medium:
    name: "2단"
    icon: mdi:circle-slice-5
  fan_high:
    name: "3단"
    icon: mdi:circle-slice-7

automation:
# - alias: restart_wallpad_addon
#   trigger:
#     - platform: template
#       value_template: "{{ is_state('sensor.wallpad_addon_state', 'stopped') }}"
#   action:
#     - service: hassio.addon_start
#       data:
#         addon: "25b6f150_wallpad"
  - alias: fan_update_bool_off
    trigger:
    - platform: template
      value_template: "{{ states.fan.fan1.state == 'off' }}"
    action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_low
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_medium
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_high
  - alias: fan_update_bool_low
    trigger:
    - platform: template
      value_template: "{{ states.fan.fan1.state == 'on' and states.fan.fan1.attributes.speed == 'low' }}"
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_off
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_low
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_medium
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_high
  - alias: fan_update_bool_medium
    trigger:
    - platform: template
      value_template: "{{ states.fan.fan1.state == 'on' and states.fan.fan1.attributes.speed == 'medium' }}"
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_low
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_medium
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_high
  - alias: fan_update_bool_high
    trigger:
    - platform: template
      value_template: "{{ states.fan.fan1.state == 'on' and states.fan.fan1.attributes.speed == 'high' }}"
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_off
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_low
    - service: input_boolean.turn_off
      entity_id: input_boolean.fan_medium
    - service: input_boolean.turn_on
      entity_id: input_boolean.fan_high
